### PR TITLE
Remove debug param. It increases frozen and RAM by 800ish bytes.

### PR DESCRIPTION
**Pull request by tannewt**

### CODE REVIEW

**Review by kattni — APPROVED** [review]
Looks good, thanks for looking into this.

**Comment by ladyada** [comment]
oi - this code was handy - i guess maybe we can make different version of the library called `busdevice_debug`?

**Comment by barbudor** [comment]
Is there anything in Python that could offer conditional compilation like #if if C?
Something that mpy-cross could easily remove?

**Comment by ladyada** [comment]
not really - eveything is interpretted :)

**Pull request merged**
