### PR TITLE
SPI has no address

### PR DESCRIPTION
**Pull request by mstaack**

### CODE REVIEW

**Comment by ladyada** [comment]
its true! however, now pylint has a complaint...
@dherrada can you assist in getting pylint happy :)

**Comment by caternuson** [comment]
Weird. Looks like there was an attempt to turn that check off. Wonder why it's only failing now. Maybe need to move the disable up a bit in scope?
```python
        except OSError:
            # some OS's dont like writing an empty bytesting...
            # Retry by reading a byte
            # pylint: disable=raise-missing-from
            try:
                result = bytearray(1)
                self.i2c.readfrom_into(self.device_address, result)
            except OSError:
                raise ValueError("No I2C device at address: 0x%x" % self.device_address)
            # pylint: enable=raise-missing-from
```

**Comment by evaherrada** [comment]
@ladyada sure thing

**Comment by evaherrada** [comment]
@ladyada Ok. This is passing

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
great teamwork! merged!

**Pull request merged**
