### PR TITLE
Removed building locally section from README, replaced with documenta…

### PR DESCRIPTION
**Pull request by evaherrada**
…tion section

### CODE REVIEW

**Review by siddacious — CHANGES_REQUESTED** [review]
I think this one also needs the PyPi instructions?

**Comment by evaherrada** [comment]
@siddacious It wasn't on the spreadsheet that @kattni gave me of the ones to add pypi to, but I could have copied it wrong.

**Comment by evaherrada** [comment]
@siddacious Should I remove the "to install" section?

**Review by kattni — DISMISSED** [review]
Leave that section for now. We'll revisit this if we feel the need.

**Review by kattni — CHANGES_REQUESTED** [review]
After rereading it, yes, please remove the entire "Installation" section, it is misleading, it should not be installed directly from the repo. 

If you feel like there should be something there, direct people to https://circuitpython.org/libraries to download the appropriate bundle and link to the [Welcome to CircuitPython>CircuitPython Libraries page](https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries) for instructions.

**Comment by evaherrada** [comment]
@kattni Alright. It looks like it already directs people to the library bundle download. I'll close this PR and make another one with just the first commit.

**Pull request closed without merging**
