### PR TITLE
Update to new build process and turn on lint.

### PR DESCRIPTION
**Pull request by tannewt**
I haven't tested these changes on device yet. Please only merge you test it or I follow up later to say its tested.

For https://github.com/adafruit/circuitpython/issues/475

### CODE REVIEW

**Comment by jerryneedell** [comment]
Partially tested I2C by executing new CCS811 library example with the updated adafruit_bus_device and adafruit_register.  CCS811 access via I2c worked normally.

Also successfully tested BME280 via I2C.

**Comment by jerryneedell** [comment]
Successfully accessed BME280 via SPI. On Metro M0 Express CP 2.1.0

**Comment by tannewt** [comment]
Do those driver fully utilize bus device? I imagine they do.

**Comment by dhalbert** [comment]
This is the latest merged PR. Is this ready for a new release? I ask because I'm updating the CPX frozen modules.

**Pull request merged**
